apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo
          image: REPLACE_WITH_ECR_IMAGE
          ports:
            - containerPort: 5000
